server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/geoserviciosbd?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG